### ISSUE TITLE
No output when executing fpn module and the code exited without any error.

### ISSUE THREAD

**Issue by bobzhang123** [Lausannen/NAS-FCOS#6]
Hi, I have tested your code on coco dataset. no matter training or testing,  there is no output when executing fpn module and the code exited without any errors.the code is as follows:
in single_stage_detector.py :
![image](https://user-images.githubusercontent.com/13234596/74305361-a6fb2280-4d9a-11ea-8e44-8b8208da2ef9.png)
there is no output and the code is exited without any errors or warnnings:
![image](https://user-images.githubusercontent.com/13234596/74305418-d6119400-4d9a-11ea-8fde-4de9566684b9.png)
training script:python -m torch.distributed.launch --nproc_per_node=2 --master_port=1213 tools/train_net.py --config-file "configs/search/R_50_NAS_retinanet.yaml"
testing script:python -m torch.distributed.launch --nproc_per_node=1 tools/test_net.py --config-file "configs/search/R_50_NAS_retinanet.yaml"

Have you met this problem?could you explan the reason? thanks!

**Comment by Lausannen** [comment]
@bobzhang123 
Hi, I have tested the same scripts and everything seems normal. I haven't had the problem before either.
In your test image, the porgram printed the info "Start evaluation ...", which means it had entered test mode. Compared with the origin maskrcnn_benchmark, we remove the tqdm, so you will not see the progress bar. To solve the issue, can you please try the next steps to let me know more info ?

**Step 1:**  What kind of server does your program run on ? And what's your torch version?

**Step 2:**  Can you try to use "nohup" to redirect the output file ? Specific commands can be referred to `nohup python -m torch.distributed.launch --nproc_per_node=1 tools/test_net.py --config-file "configs/search/R_50_NAS_retinanet.yaml >test_retinanet.out 2>&1 &"`
Since the program may need to wait for the buffer to fill before it prints to the screen.

**Step 3:** When you run the test program, you can use `watch -n 1 nvidia-smi` to monitor the GPUs utils, if GPUs are working normally, you may wait a few miniuts to see if everything is ok.
Please feel free to let me know any problem.

**Comment by bobzhang123** [comment]
@Lausannen much thanks for your reply!
Q1: I use linux server with two P100 GPUS, torch vision is 1.0.0 as you suggested.
Q2:I have tried the the command you provided，and the log is same as before, there is still no output when executing fpn module!
![image](https://user-images.githubusercontent.com/13234596/74312617-02cea700-4dad-11ea-96ca-2efce49c81e7.png)

Q3:I have tried the command nvidia-smi,  after a while, the code exited, no PIDs was showed, and the GPUs did not work.
I haven't changed any code when testing except some, What a strange problem！

**Comment by Lausannen** [comment]
@bobzhang123 That's really confusing since no extra info has been reported. I will download the repository and create an independent environment to check each steps. Any new change will be upload in time. You may change the config-file to see if others can be worked normally.
If I can't duplicate the problem here, I will upload a full environment on cloud to help you run on your machine. Any new discovery please let me know. Thanks!

**Comment by bobzhang123** [comment]
@Lausannen much thanks! I will keep following your work! If I find any new question, I will tell you immediately.

**Comment by bobzhang123** [comment]
@Lausannen I have found the problem, My GCC version is only 4.8.5, after I update the GCC version, I can take training and tesing normally.
Thanks a lot!
